### PR TITLE
Bump version to 0.2.0

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release add a changelog entry and bump the version number.

### CODE REVIEW

**Comment by tcharding** [comment]
Tagged and published.

cc @DanGould

**Comment by DanGould** [comment]
I'm a bit confused about the upgrade, it seemed on an incomplete draft you wanted someone to check whether or not the soon-to-be finished port was a character-for-character copy from rust-bitcoin, but then it got merged.

Did I misunderstand your request? Glad this was published in any case

**Comment by tcharding** [comment]
Oh I just assumed that no one would do it, I also realised that this crate claims to be a copy right from the start so any user would likely want to verify that them self anyways and this patch does not change that.

**Comment by tcharding** [comment]
I also put a bunch more effort into the `v2` stuff so it was good to go, IMO.

**Pull request merged**
