### PR TITLE
Add BIP-174 test vectors

### PR DESCRIPTION
**Pull request by tcharding**
Add all the test vectors:

- The parsing stuff is re-written from scratch
- The complex stuff in `bip-174.rs` is copied directly from `rust-bitcoin/bitcoin/tests/psbt.rs` where it was written by myself, Dan, and Armin.
- The signer checks stuff is written new, it never existed in `rust-bitcoin`

See co-developed-by tag for email addresses of the other two devs.

### CODE REVIEW

**Comment by tcharding** [comment]
Hey @DanGould  I copied the stuff from `rust-bitcoin` that you and I wrote last year. Some of the commits from then include a fella named Armin but I don't remember his github username. I kept his name in a `co-developed-by` tag in the patch out of courtesy.

**Comment by tcharding** [comment]
Force push adds the signer checks, with a couple of todo's left in there. The code is pretty racy.

**Comment by DanGould** [comment]
I'm sure @armins88 would understand

**Comment by 0xBEEFCAF3** [comment]
All good here!
Thanks @tcharding

**Comment by tcharding** [comment]
Legend, thanks.

**Pull request merged**
